# Generated by Django 2.0.5 on 2018-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
            ],
        ),
    ]
