# Generated by Django 2.0.4 on 2018-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrudbasico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('profesor', models.CharField(max_length=30)),
                ('intensidad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Maestros',
        ),
    ]
