# Generated by Django 2.0.2 on 2018-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrudbasico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_entrega', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Maestros',
        ),
    ]
