# Generated by Django 2.0.5 on 2018-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrudbasico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=2)),
            ],
        ),
    ]
