# Generated by Django 2.0.2 on 2018-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrudbasico', '0002_auto_20180505_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='codigo',
        ),
        migrations.AddField(
            model_name='actividades',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
