# Generated by Django 2.0.5 on 2018-05-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrudbasico', '0002_auto_20180505_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
