# Generated by Django 2.0.2 on 2018-05-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcrudbasico', '0003_auto_20180505_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividades',
            old_name='id',
            new_name='codigo',
        ),
    ]
